### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by njchandu** [keepcosmos/beanmother#18]
1. Is it possible to create a bean object for an object which is not at the root level?
Ex:
```
my:
  book: &book
    id: ${sequence.number}
    title: ${faker.book.title}
    language: en
    publishedAt: ${faker.date.between('2000-01-01', '2010-01-01')}

  author:
    id: ${sequence.number}
    works:
      - <<: *book
      - <<: *book
      - <<: *book
    somethingElse: bla
```

2.  Is it possible to create a bean for a specific object in a specific file if there are duplicate yaml objects.
Ex: 
```
first.yml
book: &book
  id: 1
  title: ${faker.book.title}
  language: en
  publishedAt: ${faker.date.between('2000-01-01', '2010-01-01')}
```
and
```
second.yml
book: &book
  id: 2
  title: ${faker.book.title}
  language: en
  publishedAt: ${faker.date.between('2000-01-01', '2010-01-01')}
```
