### ISSUE TITLE
How to query

### ISSUE THREAD

**Issue by njchandu** [keepcosmos/beanmother#20]
This is a `how to query`. Apologies if this is not the right place to post queries:

```
book: &book
  id: ${sequence.number}
  title: ${faker.book.title}
  publishedAt: &anchor_val2 ${faker.date.between('2000-01-01', '2010-01-01')}

author:
  id: ${sequence.number}
  policies:
    id1:
      id: ${sequence.number}
      title: ${faker.book.title}
      publishedAt: *anchor_val2
    id2:
      id: ${sequence.number}
      title: ${faker.book.title}
      publishedAt: ${current.date}
```

Using yaml anchors here, `publishedAt: *anchor_val2` generates new `${faker.date.between('2000-01-01', '2010-01-01')}`

Is there a way I can reference (reuse) the data generated in `publishedAt: &anchor_val2 ${faker.date.between('2000-01-01', '2010-01-01')}`
