### ISSUE TITLE
Is it possible to use Pair object to translate the yml data

### ISSUE THREAD

**Issue by njchandu** [keepcosmos/beanmother#21]
```
author:
  id: ${sequence.number}
  policies:
    id2:
      id: ${sequence.number}
      title: ${faker.book.title}
      pubInfo:
        publishedAt: ${current.date}
        publishedAt: ${faker.date.between('2020-01-01', '2030-01-01')}
```
Is it possible to translate it to
```
private Pair<String, Book> policies;
```
I'm able to read it into a map though.
```
private Map<String, Book> policies;
```

Thanks in advance!
