### ISSUE TITLE
Script inside _construct not working

### ISSUE THREAD

**Issue by tsuharesu** [keepcosmos/beanmother#31]
I'm using this with Kotlin data classes, they don't have default constructors. Since I can use `_construct` this shouldn't be a problem. However, when trying to create a class with a script `${sequence.number}`, Beanmother gives an exception that my class doesn't have a default constructor.

This works:
```yml
valid_account:
  _construct:
    - 1 # Int
    - Roxo # String
    - 'BRL 0.00' # BigMoney
```

This doesn't:
```yml
valid_account:
  _construct:
    - ${sequence.number} # Int
    - Roxo # String
    - 'BRL 0.00' # BigMoney
```

Is this the correct behavior? Shouldn't scripts work anywhere?
